String restImagesFolderName = 'Restaurant_Registeration';
String restOwnerIdImageFolder = '/restaurant_Id_Images';

List<String> cusines = [
  "American",
  "BBQ",
  "Breakfast",
  "Burgers",
  "Cafe",
  "Chinese",
  "Desserts",
  "French",
  "Greek",
  "Healthy",
  "Indian",
  "Italian",
  "Japanese",
  "Mexican",
  "Noodles",
  "Organic",
  "Pasta",
  "Pizza",
  "Salads",
  "Fastfood",
  "Seafood",
  "Spanish",
  "Steak",
  "Sushi",
  // "Tacos",
  // "Tapas",
  "Vegan",
];

List<String> cusineImages = [
  'lib/assets/images/cusineslist/American.png',
  'lib/assets/images/cusineslist/barbecue.png',
  'lib/assets/images/cusineslist/Breakfast.png',
  'lib/assets/images/cusineslist/Burger.png',
  'lib/assets/images/cusineslist/cafe.png',
  'lib/assets/images/cusineslist/chinese.png',
  'lib/assets/images/cusineslist/Dessert.png',
  'lib/assets/images/cusineslist/French.png',
  'lib/assets/images/cusineslist/Greek.png',
  'lib/assets/images/cusineslist/Healthy.png',
  'lib/assets/images/cusineslist/Indian.png',
  'lib/assets/images/cusineslist/Italian.png',
  'lib/assets/images/cusineslist/Japanese.png',
  'lib/assets/images/cusineslist/Mexican.png',
  'lib/assets/images/cusineslist/Noodles.png',
  'lib/assets/images/cusineslist/Organic.png',
  'lib/assets/images/cusineslist/Pasta.png',
  'lib/assets/images/cusineslist/Pizza.png',
  'lib/assets/images/cusineslist/Salad.png',
  'lib/assets/images/cusineslist/Fastfood.png',
  'lib/assets/images/cusineslist/Seafood.png',
  'lib/assets/images/cusineslist/Spanish.png',
  'lib/assets/images/cusineslist/Steak.png',
  'lib/assets/images/cusineslist/Sushi.png',
  'lib/assets/images/cusineslist/Vegan.png',
];
