String supabaseUrl = 'https://mrqaapzhzeqvarrtfkgv.supabase.co';
String supabasekey =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ycWFhcHpoemVxdmFycnRma2d2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjI3OTc4NTIsImV4cCI6MjAzODM3Mzg1Mn0.mdcsEEmN9dSmY1pbEIOlluUsvNmdrItsQ453omyrxsM';
